services:
  db:
    image: docker.io/postgres:alpine
    shm_size: 128mb
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    volumes:
      - ./data:/var/lib/postgresql:rw
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro

volumes:
  db-data:

